apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gep-dev-system-entry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gep-dev-system-entry
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: Always
          image: nginx:latest
          ports:
            - name: http-port
              containerPort: 80
