apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: gep-dev-logging
  labels:
    app: elasticsearch
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Gi

