apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gep-dev-telimetry
  name: gep-dev-telimetry
  namespace: gep-dev-201902
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gep-dev-telimetry
    spec:
      containers:
      - name: vault-container
        image: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-geppetto-2019
      - name: prometheus-container
        image: prom/prometheus:v2.1.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus/"
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
          - name: prometheus-storage-volume
            mountPath: /prometheus/    
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}  
