apiVersion: v1
kind: Service
metadata:
  name: gep-dev-telimetry
  namespace: gep-dev-201902
  labels:
    app: gep-dev-telimetry
spec:
  type: LoadBalancer
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
    - name: prometheus
      targetPort: 9090
      port: 9090  
  selector:
    app: gep-dev-telimetry
