apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gep-dev-ops-db
spec:
  replicas: 1
  template:
    metadata:
      name: gep-dev-ops-db
      labels:
        name: gep-dev-ops-db
    spec:
      containers:
        - name: sonar-postgres-container
          imagePullPolicy: Always
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: T@ng3456
            - name: POSTGRES_USER
              value: sonar
            - name: POSTGRES_DB
              value: sonar  
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            # This name must match the volumes.name below.
            - name: sonar-postgres-data
              mountPath: /var/postgresData
      volumes:
        - name: sonar-postgres-data
          persistentVolumeClaim:
            claimName: gep-dev-ops-postgres-pvc
