apiVersion: v1
kind: Service
metadata:
  labels:
    name: gep-dev-ops-db
  name: gep-dev-ops-db
spec:
  type: NodePort
  ports:
    - name: sonar-postgres
      port: 5432
      targetPort: 5432
  selector:
    name: gep-dev-ops-db
