kind: PersistentVolume
apiVersion: v1
metadata:
  name: gep-dev-ops-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gep-dev-ops-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
          
