apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gep-dev-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gep-dev-app
    spec:
      containers:
        - name: node-container
          imagePullPolicy: Always
          image: tharanirajan/gep-dev-node-app:1.0
          ports:
            - name: http-port
              containerPort: 3000
          env:
            - name: gep-dev-app-db
              value: gep-dev-app-db
